# Nixpacks configuration for Railway deployment
# Ensures proper OpenSSL compatibility for Prisma

[phases.setup]
nixPkgs = ["openssl", "openssl.dev", "pkg-config"]

[phases.build]
cmds = [
  "npm ci",
  "npm run railway:build"
]

[phases.start]
cmd = "npm run railway:start"

[variables]
PRISMA_CLI_BINARY_TARGETS = "linux-musl-openssl-3.0.x"
OPENSSL_STATIC = "1"